language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

after_success:
  - mvn clean cobertura:cobertura coveralls:report

notifications:
  email:
    recipients:
      - e1225561@student.tuwien.ac.at
      - e1128004@student.tuwien.ac.at
      - e1228830@student.tuwien.ac.at
      - e1325306@student.tuwien.ac.at
      - paris.philipp@gmail.com
      - emmanuelpescosta099@gmail.com
    on_success: change
    on_failure: always